### ISSUE TITLE
Port to 5.10.x kernel

### ISSUE THREAD

**Issue by myzar** [Cpasjuste/rpi-dpidac#1]
Hi , i've tried to compile it with the new 5.10.x kernel , but it fails and i've noticed that many things are different and i'm not skilled enough, can you try to port it to the new kernel ?

**Comment by osvathrobi** [comment]
I ported it to those kernel headers. Just be mindful that if you want a 480i output you will need a patched vc4 kms module - so no real use on the stock module. https://github.com/osvathrobi/rpi-dpidac

**Comment by myzar** [comment]
Well i don't need 480i , I'm using 320p with the jammapi so it's good for me and it works, thx!

**Comment by Cpasjuste** [comment]
Fixed, thanks @osvathrobi
